name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        required: true
        type: choice
        options:
          - default
          - dev
          - prod

jobs:
  Infrastructure-Deployment:
    name: Deploy Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Infra

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.5

    - name: Terraform Init
      run: terraform init

    - name: Select workspace
      run: terraform workspace select -or-create ${{ github.event.inputs.environment }}

    - name: Deploy infrastructure
      run: |
        cd env/${{ github.event.inputs.environment }}
        terraform plan 

    - name: Terraform Apply
      run: terraform apply --auto-approve 

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}