name: rabbit-mq

on:
  workflow_dispatch:

jobs:
  build-and-push:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy using Helm
        env:
          # KUBERNETES_NAMESPACE: ${{ secrets.KUBERNETES_NAMESPACE }}
          HELM_RELEASE_NAME: rabbit-mq
          HELM_CHART_PATH: helm/rabbit-mq
        run: helm upgrade --install $HELM_RELEASE_NAME $HELM_CHART_PATH
